/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
<<<<<<< HEAD
    CustomSlider: typeof import('./src/components/CustomSlider.vue')['default']
=======
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
>>>>>>> f49502d1123334f214a8a3684b1c1c41aaa28499
  }
}
